server:
  port: 8082

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: orders.exchange
    queue: orders.queue
    routing-key: orders.created
